from datetime import datetime

def generate_diagnostic_report_text(result):
    """
    Generates a clean text/markdown diagnostic report for a predicted leaf sample.
    """
    if not result.get('success', False):
        return f"DIAGNOSTIC REPORT GENERATION FAILED: {result.get('error', 'Unknown Error')}"

    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    advisory = result.get('advisory', {})
    display_name = result.get('predicted_class_display', 'Unknown')
    confidence = result.get('confidence_percentage', 0.0)
    severity = advisory.get('severity', 'N/A')
    cause = advisory.get('cause', 'N/A')
    
    symptoms_str = "\n".join([f"  - {s}" for s in advisory.get('symptoms', [])])
    organic_str = "\n".join([f"  - {o}" for o in advisory.get('organic_treatment', [])])
    chemical_str = "\n".join([f"  - {c}" for c in advisory.get('chemical_treatment', [])])
    prevention_str = "\n".join([f"  - {p}" for p in advisory.get('prevention', [])])
    
    warning_str = f"WARNING / NOTE: {result['domain_warning']}\n" if result.get('domain_warning') else ""
    
    report = f"""================================================================================
                    TEA LEAF DISEASE DIAGNOSTIC REPORT
================================================================================
Date & Time        : {now_str}
Diagnosis Status   : {result.get('validation_status', 'PASSED')}
Leaf Domain Check  : {'PASS (Foliage pigments detected)' if result.get('is_leaf_like') else 'WARNING (Low leaf pigment ratio)'}
{warning_str}
--------------------------------------------------------------------------------
1. DIAGNOSIS RESULTS
--------------------------------------------------------------------------------
Primary Diagnosis  : {display_name}
Confidence Score   : {confidence}%
Severity Level     : {severity}
Biological Cause   : {cause}

Top Class Probabilities:
"""
    for item in result.get('class_probabilities', [])[:4]:
        report += f"  - {item['display_name']:<25}: {item['percentage']}%\n"
        
    report += f"""
--------------------------------------------------------------------------------
2. KEY SYMPTOMS
--------------------------------------------------------------------------------
{symptoms_str}

--------------------------------------------------------------------------------
3. ORGANIC & BIOLOGICAL CONTROL
--------------------------------------------------------------------------------
{organic_str}

--------------------------------------------------------------------------------
4. RECOMMENDED CHEMICAL TREATMENT
--------------------------------------------------------------------------------
{chemical_str}

--------------------------------------------------------------------------------
5. PREVENTIVE & CULTURAL MANAGEMENT
--------------------------------------------------------------------------------
{prevention_str}

================================================================================
Disclaimer: This report was generated by AI-Based Tea Leaf Disease Detection System.
For severe plantation outbreaks, consult a certified agricultural officer.
================================================================================
"""
    return report

